# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dq85ATiakqu3286ImJbHrchUIu9TzGrv
"""



"""### 4.4 Model Training and Evaluation

#### 4.4.1 Logistic Regression
"""

from sklearn.linear_model import LogisticRegression

# Initialize and train the Logistic Regression model with balanced class weight
# max_iter is increased for convergence with scaled data
log_reg = LogisticRegression(random_state=42, class_weight='balanced', max_iter=1000)
log_reg.fit(X_train, y_train)

# Make predictions
y_pred_log_reg = log_reg.predict(X_test)

# Get prediction probabilities for ROC-AUC
y_prob_log_reg = log_reg.predict_proba(X_test)

# Evaluate the model
evaluate_model('Logistic Regression', y_test, y_pred_log_reg, y_prob_log_reg)

"""### 4.4.2 Addressing Data Leakage: Re-evaluating Logistic Regression without `satisfaction_rating`"""

import numpy as np

# Remove 'satisfaction_rating' and 'learning_experience_index' due to suspected data leakage
X_leakage_free = X.drop(columns=['satisfaction_rating', 'learning_experience_index'])

# Split the data into training and testing sets again with the modified features
X_train_leakage_free, X_test_leakage_free, y_train_leakage_free, y_test_leakage_free = train_test_split(
    X_leakage_free, y, test_size=0.2, random_state=42, stratify=y
)

# Re-initialize and train the Logistic Regression model with balanced class weight
log_reg_leakage_free = LogisticRegression(random_state=42, class_weight='balanced', max_iter=1000)
log_reg_leakage_free.fit(X_train_leakage_free, y_train_leakage_free)

# Make predictions
y_pred_log_reg_leakage_free = log_reg_leakage_free.predict(X_test_leakage_free)

# Get prediction probabilities for ROC-AUC
y_prob_log_reg_leakage_free = log_reg_leakage_free.predict_proba(X_test_leakage_free)

# Evaluate the model
evaluate_model('Logistic Regression (Leakage-Free - Attempt 2)', y_test_leakage_free, y_pred_log_reg_leakage_free, y_prob_log_reg_leakage_free)

"""#### 4.4.3 Decision Tree Classifier"""

from sklearn.tree import DecisionTreeClassifier

# Initialize and train the Decision Tree model with balanced class weight
decision_tree = DecisionTreeClassifier(random_state=42, class_weight='balanced')
decision_tree.fit(X_train_leakage_free, y_train_leakage_free)

# Make predictions
y_pred_decision_tree = decision_tree.predict(X_test_leakage_free)

# Get prediction probabilities for ROC-AUC
y_prob_decision_tree = decision_tree.predict_proba(X_test_leakage_free)

# Evaluate the model
evaluate_model('Decision Tree Classifier (Leakage-Free)', y_test_leakage_free, y_pred_decision_tree, y_prob_decision_tree)

"""#### 4.4.4 Random Forest Classifier"""

from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Random Forest model with balanced class weight
random_forest = RandomForestClassifier(random_state=42, class_weight='balanced')
random_forest.fit(X_train_leakage_free, y_train_leakage_free)

# Make predictions
y_pred_random_forest = random_forest.predict(X_test_leakage_free)

# Get prediction probabilities for ROC-AUC
y_prob_random_forest = random_forest.predict_proba(X_test_leakage_free)

# Evaluate the model
evaluate_model('Random Forest Classifier (Leakage-Free)', y_test_leakage_free, y_pred_random_forest, y_prob_random_forest)

"""#### 4.4.5 XGBoost Classifier"""

import xgboost as xgb

# Initialize and train the XGBoost Classifier
# For binary classification with imbalanced datasets, using `scale_pos_weight` is often preferred
# instead of `class_weight` directly as in scikit-learn.
# It is calculated as count(negative_examples) / count(positive_examples).
scale_pos_weight_value = (y_train_leakage_free == 0).sum() / (y_train_leakage_free == 1).sum()

xgb_model = xgb.XGBClassifier(
    objective='binary:logistic', # For binary classification
    eval_metric='logloss',       # Evaluation metric
    use_label_encoder=False,     # Suppress warning for older label encoder behavior
    random_state=42,
    scale_pos_weight=scale_pos_weight_value # Handle class imbalance
)
xgb_model.fit(X_train_leakage_free, y_train_leakage_free)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test_leakage_free)

# Get prediction probabilities for ROC-AUC
y_prob_xgb = xgb_model.predict_proba(X_test_leakage_free)

# Evaluate the model
evaluate_model('XGBoost Classifier (Leakage-Free)', y_test_leakage_free, y_pred_xgb, y_prob_xgb)

"""#### 4.4.6 Support Vector Machine (SVM) Classifier"""

from sklearn.svm import SVC

# Initialize and train the Support Vector Machine model with balanced class weight
# Using 'balanced' for class_weight to handle imbalance
# Setting probability=True to enable predict_proba for ROC-AUC calculation, though it can be slow for large datasets
svm_model = SVC(random_state=42, class_weight='balanced', probability=True)
svm_model.fit(X_train_leakage_free, y_train_leakage_free)

# Make predictions
y_pred_svm = svm_model.predict(X_test_leakage_free)

# Get prediction probabilities for ROC-AUC
y_prob_svm = svm_model.predict_proba(X_test_leakage_free)

# Evaluate the model
evaluate_model('SVM Classifier (Leakage-Free)', y_test_leakage_free, y_pred_svm, y_prob_svm)

"""#### 4.4.7 Hyperparameter Tuning for SVM (GridSearchCV)"""

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, make_scorer

# Define the parameter grid for GridSearchCV
# Focusing on C, kernel, and gamma which are key for SVC performance
param_grid = {
    'C': [0.1, 1, 10, 100], # Regularization parameter
    'kernel': ['rbf', 'linear'], # Kernel type
    'gamma': ['scale', 'auto', 0.1, 1] # Kernel coefficient for 'rbf', 'poly' and 'sigmoid'
}

# Define a custom scorer to optimize for precision of the 'Dropped' class (label 0)
# Since 'Dropped' is the minority class and our primary concern for recall, we explicitly target it.
# Our y is mapped: 'Completed': 1, 'Dropped': 0.
precision_scorer_dropped = make_scorer(precision_score, pos_label=0)

# Initialize GridSearchCV
# We use the leakage-free training data (X_train_leakage_free, y_train_leakage_free)
# and aim to optimize for the precision of the 'Dropped' class.
# class_weight='balanced' is retained to handle the overall imbalance.
grid_search_svm = GridSearchCV(
    SVC(random_state=42, class_weight='balanced', probability=True), # probability=True for ROC-AUC
    param_grid,
    scoring=precision_scorer_dropped,
    cv=5, # 5-fold cross-validation
    n_jobs=-1, # Use all available CPU cores
    verbose=2
)

# Fit GridSearchCV to the training data
print("Starting GridSearchCV for SVM...")
grid_search_svm.fit(X_train_leakage_free, y_train_leakage_free)

print("GridSearchCV for SVM completed.")

# Get the best parameters and best score
best_params_svm = grid_search_svm.best_params_
best_score_svm = grid_search_svm.best_score_

print(f"\nBest Hyperparameters for SVM: {best_params_svm}")
print(f"Best Cross-validation Precision (for 'Dropped' class): {best_score_svm:.4f}")

# Get the best estimator
best_svm_model = grid_search_svm.best_estimator_

# Make predictions with the best model
y_pred_best_svm = best_svm_model.predict(X_test_leakage_free)
y_prob_best_svm = best_svm_model.predict_proba(X_test_leakage_free)

# Evaluate the best model
evaluate_model('Tuned SVM Classifier (Leakage-Free)', y_test_leakage_free, y_pred_best_svm, y_prob_best_svm)

"""## 4.5 Model Comparison Table

| Model | Accuracy | Precision | Recall | F1-Score | ROC-AUC |
|:------------------------------------|:---------|:----------|:---------|:---------|:--------|
| Logistic Regression | 0.5885 | 0.23 | 0.57 | 0.33 | 0.6022 |
| Decision Tree | 0.6890 | 0.18 | 0.21 | 0.20 | 0.5033 |
| Random Forest | 0.8214 | 0.00 | 0.00 | 0.00 | 0.5380 |
| XGBoost | 0.7384 | 0.22 | 0.18 | 0.20 | 0.5300 |
| Tuned SVM | 0.5534 | 0.23 | 0.64 | 0.34 | 0.6111 |
"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Assuming y_test_leakage_free contains the true labels
# And y_prob_..._leakage_free contain probabilities for the positive class (Completed = 1)

models = {
    'Logistic Regression': y_prob_log_reg_leakage_free,
    'Decision Tree': y_prob_decision_tree,
    'Random Forest': y_prob_random_forest,
    'XGBoost': y_prob_xgb,
    'Tuned SVM': y_prob_best_svm
}

plt.figure(figsize=(10, 8))

for name, y_prob in models.items():
    # Ensure we get probabilities for the positive class (1, 'Completed')
    # All y_prob arrays are structured with class 0 probabilities in column 0 and class 1 in column 1
    fpr, tpr, _ = roc_curve(y_test_leakage_free, y_prob[:, 1])
    roc_auc = roc_auc_score(y_test_leakage_free, y_prob[:, 1])
    plt.plot(fpr, tpr, label=f'{name} (AUC = {roc_auc:.4f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Classifier (AUC = 0.5000)')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison of Models')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

print("ROC curve comparison plot generated.")

"""## 4.6 Conclusion on Model Performance

The comparative evaluation indicates that the Support Vector Machine with optimized hyperparameters achieved the highest overall predictive performance, as evidenced by its superior F1-score and ROC-AUC for the 'Dropped' class. Consequently, the tuned SVM model was selected as the final predictive model for subsequent explainability and fairness analyses.

## 4.7 Saving the Best Model and Scaler

To ensure reproducibility and enable future deployment, the best-tuned SVM model and the `StandardScaler` used for feature scaling will be saved.
"""

import joblib

# Save the best SVM model
joblib.dump(best_svm_model, 'best_svm_model.pkl')
print("Best SVM model saved as 'best_svm_model.pkl'")

# Save the StandardScaler
joblib.dump(scaler, 'scaler.pkl')
print("StandardScaler saved as 'scaler.pkl'")