# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dq85ATiakqu3286ImJbHrchUIu9TzGrv
"""



"""## 3.3.1 Identify Numerical Features for Scaling

### Subtask:
Identify all numerical features in the `df_processed` DataFrame that need to be scaled. Exclude any identifier columns like 'student_id'.

"""

print("Numerical features identified for scaling:")
print(numerical_cols_for_corr)

"""## 3.3.2 Apply StandardScaler


"""

from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the numerical features and transform them
df_processed[numerical_cols_for_corr] = scaler.fit_transform(df_processed[numerical_cols_for_corr])

print("Numerical features scaled successfully using StandardScaler.")
print("First 5 rows of df_processed with scaled numerical features:")
print(df_processed.head())

print("Descriptive statistics for scaled numerical features:")
print(df_processed[numerical_cols_for_corr].describe().loc[['mean', 'std']])

"""## 3.3.3 Identify Numerical Features



"""

numerical_features = df_processed.select_dtypes(include=['int64', 'float64']).columns.tolist()
numerical_features = [col for col in numerical_features if col != 'student_id']

print("Numerical features in df_processed (excluding 'student_id'):")
print(numerical_features)

print("Descriptive statistics for scaled numerical features (mean and std dev):")
print(df_processed[numerical_features].describe().loc[['mean', 'std']])

"""## 3.3.4 Identify Categorical Features



"""

categorical_features_to_encode = df_processed.select_dtypes(include='object').columns.tolist()
categorical_features_to_encode.remove('completion_status') # Exclude target variable

print("Categorical features identified for encoding:")
print(categorical_features_to_encode)

"""## Apply One-Hot Encoding



"""

df_processed_encoded = pd.get_dummies(df_processed, columns=categorical_features_to_encode, drop_first=True)

print("First 5 rows of df_processed after one-hot encoding:")
print(df_processed_encoded.head())

print('\nDataFrame Info after one-hot encoding:')
df_processed_encoded.info()

"""## 3.3.5 Verify Encoded Data



"""

print("Shape of df_processed_encoded:", df_processed_encoded.shape)

print("\nFirst 5 rows of df_processed_encoded after one-hot encoding verification:")
print(df_processed_encoded.head())

print("\nBoolean (one-hot encoded) columns:")
print(df_processed_encoded.select_dtypes(include='bool').columns.tolist())

"""## 3.3.6 Domain-Derived Features

#### Domain-Derived Features

To improve the predictive capability of the machine learning models, additional domain-derived features were engineered by combining related variables into meaningful composite indicators. An **Engagement Score** was created by averaging the assignment completion rate, percentage of videos watched, and forum participation to represent the learner's overall engagement in the online course. An **Academic Index** was derived from the average of quiz scores and assignment completion rates to provide a summary measure of academic performance. Likewise, a **Learning Experience Index** was generated by combining the number of previously completed courses and the learner satisfaction rating to capture prior online learning experience and overall learning perception. These engineered features incorporate domain knowledge into the dataset, providing higher-level representations of learner behavior that can improve the predictive performance and interpretability of the machine learning models.

## Create Engagement Score

### Subtask:
Create a new feature 'engagement_score' by combining 'assignment_completion_rate', 'videos_watched_pct', and 'forum_posts'.
"""

df_processed_encoded['engagement_score'] = df_processed_encoded[['assignment_completion_rate', 'videos_watched_pct', 'forum_posts']].mean(axis=1)

print("First 5 rows of df_processed_encoded with 'engagement_score' column:")
print(df_processed_encoded.head())

"""## Create Academic Index

### Subtask:
Create a new feature 'academic_index' by combining 'quiz_scores_avg' and 'assignment_completion_rate'.

"""

df_processed_encoded['academic_index'] = df_processed_encoded[['quiz_scores_avg', 'assignment_completion_rate']].mean(axis=1)

print("First 5 rows of df_processed_encoded with 'academic_index' column:")
print(df_processed_encoded.head())

"""## Create Learning Experience Index

### Subtask:
Create a new feature 'learning_experience_index' by combining 'previous_courses_completed' and 'satisfaction_rating'.

"""

df_processed_encoded['learning_experience_index'] = df_processed_encoded[['previous_courses_completed', 'satisfaction_rating']].mean(axis=1)

print("First 5 rows of df_processed_encoded with 'learning_experience_index' column:")
print(df_processed_encoded.head())

"""## 3.4 Feature Selection

## 3.4.1 Feature Importance Analysis and Selection

To perform feature selection, we will use a `RandomForestClassifier` to identify the most important features. This involves training the model, extracting feature importances, and then visualizing the top features.
"""

from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Prepare X (features) and y (target)
# Drop 'student_id' as it's an identifier and not a feature, and 'completion_status' as it's the target
X = df_processed_encoded.drop(columns=['student_id', 'completion_status'])
y = df_processed_encoded['completion_status']

# Encode the target variable: 'Completed' to 1, 'Dropped' to 0
y = y.map({'Completed': 1, 'Dropped': 0})

# Initialize and train a RandomForestClassifier
# Using a fixed random_state for reproducibility
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X, y)

# Get feature importances
feature_importances = rf_model.feature_importances_

# Create a DataFrame for better visualization and sorting
features_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': feature_importances
})

# Sort features by importance
features_df = features_df.sort_values(by='Importance', ascending=False)

print("Top 15 most important features:\n")
print(features_df.head(15).to_markdown(index=False))

# Visualize the top 15 most important features
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=features_df.head(15), palette='viridis')
plt.title('Top 15 Most Important Features')
plt.xlabel('Feature Importance')
plt.ylabel('Feature Name')
plt.tight_layout()
plt.show()

print("Bar chart of top 15 feature importances generated.")

# Select the top N features based on importance
top_n_features = 15 # You can change this number
selected_features = features_df['Feature'].head(top_n_features).tolist()

print(f"Selected Top {top_n_features} Features for Modeling:\n")
print(selected_features)

"""## 3.5 Dimensionality Reduction (PCA)

Principal Component Analysis (PCA) is a powerful technique for dimensionality reduction. It transforms a large set of variables into a smaller one that still contains most of the information in the large set. This can help to simplify models, reduce noise, and improve computational efficiency. Here, we'll apply PCA to the complete preprocessed feature set (`X`) to explore its structure.
"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np

# Initialize PCA
pca = PCA()

# Fit PCA to the full preprocessed feature set (X)
pca.fit(X)

# Plot the cumulative explained variance ratio
plt.figure(figsize=(10, 6))
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('Number of Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Cumulative Explained Variance by Number of Principal Components')
plt.grid(True)
plt.show()

print("Explained variance plot generated.")

import seaborn as sns

# Reduce dimensions to the first two principal components for visualization
pca_2d = PCA(n_components=2)
principal_components = pca_2d.fit_transform(X)

# Create a DataFrame for the principal components and the target variable
pca_df = pd.DataFrame(data=principal_components, columns=['Principal Component 1', 'Principal Component 2'])
pca_df['completion_status'] = y.values

# Visualize the first two principal components
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='completion_status',
    data=pca_df,
    palette='viridis',
    alpha=0.7
)
plt.title('2D PCA Scatter Plot of Principal Components, Colored by Completion Status')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.show()

print("2D PCA scatter plot generated.")

"""## 3.6 Explainability"""

import matplotlib.pyplot as plt
import seaborn as sns

# Reuse the features_df from previous feature importance analysis

plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', hue='Feature', data=features_df.head(15), palette='viridis', legend=False)
plt.title('Top 15 Most Important Features (Random Forest)')
plt.xlabel('Feature Importance')
plt.ylabel('Feature Name')
plt.tight_layout()
plt.show()

print("Bar chart of top 15 feature importances generated.")