# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dq85ATiakqu3286ImJbHrchUIu9TzGrv
"""



"""3.1.1 Loading of Dataset"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/online_learning_2026.csv')

print('First 5 rows of the DataFrame:')
print(df.head())

print('\nDataFrame Info:')
df.info()

print('\nDescriptive Statistics:')
print(df.describe())

print('\nColumn Names:')
print(df.columns.tolist())

"""3.1.2 Missing Values and Completeness of Data"""

import numpy as np

def summarize_features(df):
    feature_summary = []
    for col in df.columns:
        col_info = {
            'Feature Name': col,
            'Data Type': str(df[col].dtype),
            'Missing Values': df[col].isnull().sum()
        }

        if pd.api.types.is_numeric_dtype(df[col]):
            col_info['Category'] = 'Numerical'
            if df[col].nunique() < 20 and all(df[col].dropna().apply(lambda x: x == int(x))):
                col_info['Sub-Category'] = 'Discrete'
                col_info['Description'] = 'Counts or codes with a limited number of unique integer values.'
                col_info['Characteristics'] = f"Unique Values: {df[col].unique().tolist() if df[col].nunique() < 20 else 'Too many to list'}"
            else:
                col_info['Sub-Category'] = 'Continuous'
                col_info['Description'] = 'Measurements or quantities that can take any value within a range.'
                desc_stats = df[col].describe().loc[['mean', 'std', 'min', 'max']].to_dict()
                col_info['Characteristics'] = f"Mean: {desc_stats['mean']:.2f}, Std: {desc_stats['std']:.2f}, Min: {desc_stats['min']:.2f}, Max: {desc_stats['max']:.2f}"
        else:
            col_info['Category'] = 'Categorical'
            if df[col].nunique() / len(df) > 0.5: # Arbitrary threshold for high cardinality
                col_info['Sub-Category'] = 'Nominal (High Cardinality)'
                col_info['Description'] = 'Categories without inherent order, many unique values. Often identifiers.'
            elif df[col].nunique() <= 10:
                col_info['Sub-Category'] = 'Nominal/Ordinal'
                col_info['Description'] = 'Categories without/with inherent order, few unique values.'
            else:
                col_info['Sub-Category'] = 'Nominal'
                col_info['Description'] = 'Categories without inherent order.'
            col_info['Characteristics'] = f"Unique Values: {df[col].unique().tolist()}"

        feature_summary.append(col_info)
    return pd.DataFrame(feature_summary)

summary_df = summarize_features(df)

print("### Feature Type Summary\n")
print(summary_df.to_markdown(index=False))

# Re-confirming missing values across all columns
missing_values = df.isnull().sum()
if missing_values.sum() == 0:
    print("\n\n### Missing Values Re-confirmation\n")
    print("No missing values found across any columns. Data completeness is confirmed.")
else:
    print("\n\n### Missing Values Re-confirmation\n")
    print("Missing values detected in the following columns:\n")
    print(missing_values[missing_values > 0].to_markdown())

"""3.1.3 Initial Boxplot Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns

# Filter for numerical continuous columns from summary_df
numerical_continuous_cols = summary_df[
    (summary_df['Category'] == 'Numerical') &
    (summary_df['Sub-Category'] == 'Continuous')
]['Feature Name'].tolist()

# Exclude 'student_id' as it's an identifier and not a true continuous feature for outlier analysis
numerical_continuous_cols = [col for col in numerical_continuous_cols if col != 'student_id']

print(f"Identified Numerical Continuous Columns for Outlier Analysis: {numerical_continuous_cols}")

# Generate box plots for each numerical continuous column
plt.figure(figsize=(18, 5 * len(numerical_continuous_cols)))
for i, col in enumerate(numerical_continuous_cols):
    plt.subplot(len(numerical_continuous_cols), 2, 2*i + 1)
    sns.boxplot(y=df[col])
    plt.title(f'Box Plot of {col}')
    plt.ylabel(col)
plt.tight_layout()
plt.show()

print("Box plots generated for all numerical continuous features.")

"""3.1.4 Data Dictionary

#### Data Dictionary

A data dictionary was developed to provide a structured description of all variables included in the dataset. It summarizes the variable names, data types, measurement units or allowable values, and their corresponding descriptions. The data dictionary serves as a reference for understanding the characteristics of each feature and ensures consistency during data preprocessing, exploratory data analysis, feature engineering, and machine learning model development.

"""

data_dictionary = []

# Define descriptions for each feature based on domain knowledge
feature_descriptions = {
    'student_id': 'Unique identifier for each student.',
    'age': 'Age of the student in years.',
    'gender': 'Gender of the student.',
    'country': 'Country of residence for the student.',
    'education_level': 'Highest education level attained by the student.',
    'course_category': 'Category of the online course.',
    'platform': 'Online learning platform where the course is hosted.',
    'course_duration_weeks': 'Duration of the course in weeks.',
    'hours_per_week': 'Average number of hours a student spends on the course per week.',
    'quiz_scores_avg': 'Average score of quizzes in the course.',
    'assignment_completion_rate': 'Percentage of assignments completed by the student.',
    'forum_posts': 'Total number of posts made by the student in discussion forums.',
    'videos_watched_pct': 'Percentage of course videos watched by the student.',
    'device': 'Primary device used by the student for learning (e.g., Desktop, Mobile, Tablet).',
    'internet_speed': 'Internet speed of the student (e.g., Slow, Average, Fast).',
    'previous_courses_completed': 'Number of previous online courses completed by the student.',
    'financial_aid': 'Indicates if the student is receiving financial aid (Yes/No).',
    'course_price_usd': 'Price of the course in USD.',
    'self_motivation_score': 'Self-reported motivation score of the student (1-10).',
    'time_management_score': 'Self-reported time management score of the student (1-10).',
    'learning_disability': 'Indicates if the student has a learning disability (Yes/No).',
    'employment_status': 'Current employment status of the student.',
    'completion_status': 'Status of course completion (Completed, Dropped, In Progress).',
    'final_grade': 'Final letter grade received by the student.',
    'satisfaction_rating': 'Overall satisfaction rating of the student with the course (1-5).'
}

for index, row in summary_df.iterrows():
    col_name = row['Feature Name']
    entry = {
        'Feature Name': col_name,
        'Type': f"{row['Category']} ({row['Sub-Category']})",
        'Description': feature_descriptions.get(col_name, 'No description provided.'),
        'Characteristics': row['Characteristics']
    }
    data_dictionary.append(entry)

data_dictionary_df = pd.DataFrame(data_dictionary)

print("### Data Dictionary\n")
print(data_dictionary_df.to_markdown(index=False))

"""3.1.5 Dropping of the Column for Final Grade and removal of In progress from the completion status


#### Feature and Record Selection

Prior to model development, selected variables and records were removed to ensure the integrity and validity of the predictive analysis. The **student_id** variable was excluded because it serves only as a unique identifier and does not provide meaningful predictive information. Records with a **completion_status** of **"In Progress"** were also removed since they do not represent final learning outcomes and could introduce uncertainty into the target variable. Furthermore, the **final_grade** variable was excluded from the feature set because it is determined only after course completion and would introduce **target leakage** if used as a predictor. Removing these variables and records ensures that the machine learning models are trained using only relevant information that would realistically be available when predicting learner outcomes.

"""

df_filtered = df[df['completion_status'] != 'In Progress'].copy()
df_processed = df_filtered.drop(columns=['final_grade'])

print("First 5 rows of the processed DataFrame (after filtering and dropping 'final_grade'):")
print(df_processed.head())

print('\nDataFrame Info of the processed DataFrame:')
df_processed.info()

"""## 3.1.6 Detect Outliers using IQR


"""

print("### Outlier Detection using IQR Method\n")
outlier_results = {}

for col in numerical_continuous_cols:
    Q1 = df_processed[col].quantile(0.25)
    Q3 = df_processed[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers
    outliers = df_processed[(df_processed[col] < lower_bound) | (df_processed[col] > upper_bound)]
    num_outliers = outliers.shape[0]
    percentage_outliers = (num_outliers / len(df_processed)) * 100

    outlier_results[col] = {
        'num_outliers': num_outliers,
        'percentage_outliers': percentage_outliers
    }

    print(f"Column: {col}")
    print(f"  Q1: {Q1:.2f}")
    print(f"  Q3: {Q3:.2f}")
    print(f"  IQR: {IQR:.2f}")
    print(f"  Lower Bound: {lower_bound:.2f}")
    print(f"  Upper Bound: {upper_bound:.2f}")
    print(f"  Number of Outliers: {num_outliers}")
    print(f"  Percentage of Outliers: {percentage_outliers:.2f}%\n")

print("Outlier detection complete for all numerical continuous columns.")

"""## 3.2.7 Generate Box Plots for Key Numerical Features



"""

import matplotlib.pyplot as plt
import seaborn as sns

# Define the numerical features for which box plots are to be generated
key_numerical_features = [
    'quiz_scores_avg',
    'assignment_completion_rate',
    'hours_per_week',
    'self_motivation_score',
    'satisfaction_rating'
]

# Set up the matplotlib figure and axes for subplots
num_features = len(key_numerical_features)
plt.figure(figsize=(12, 5 * num_features))

for i, feature in enumerate(key_numerical_features):
    plt.subplot(num_features, 1, i + 1)
    sns.boxplot(data=df_processed, x='completion_status', y=feature, hue='completion_status', palette='viridis', legend=False)
    plt.title(f'Distribution of {feature} by Completion Status')
    plt.xlabel('Completion Status')
    plt.ylabel(feature)

plt.tight_layout()
plt.show()

print("Box plots generated for key numerical features against completion status.")